@startuml

package "com.studentspace.sscore.academic_course" {
    class AcademicCourse {
        - id: Long
        - name: String
       <<Getter>>
       <<Setter>>
    }

    class AcademicCourseService {
        - entityManager: EntityManager
        + getAcademicCourseListByUserId(userId: Long): List<AcademicCourse>
    }

    class AcademicCourseController {
        - courseService: AcademicCourseService
        + getAcademicCourseListByUserId(userId: Long): List<AcademicCourse>
    }
}

package "com.studentspace.sscore.user" {
    class User {
        - id: Long
        + getId(): Long
        + setId(id: Long): void
    }
}

AcademicCourse "1" -- "0..1" User : user

AcademicCourseService --> AcademicCourse : uses
AcademicCourseController --> AcademicCourseService : uses
AcademicCourseController --> AcademicRecordDto : returns

@enduml
