services:
  studentspacedb:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studentspacedb"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./:/docker-entrypoint-initdb.d/
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh


