#!/bin/bash

psql -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';"
psql -U $POSTGRES_USER -d $POSTGRES_DB -c "ALTER USER $DB_USERNAME WITH SUPERUSER;"
psql -U $POSTGRES_USER -d $POSTGRES_DB -c "ALTER DATABASE $POSTGRES_DB SET timezone TO 'localtime';"

