@startuml
actor Usuario

rectangle "Gestión de Notas Académicas" {
    Usuario --> (Gestión de notas académicas)
    (Gestión de notas académicas) --> (Crear Nota)
    (Gestión de notas académicas) --> (Editar Nota)
    (Gestión de notas académicas) --> (Eliminar Nota)
}

rectangle "Crear Nota" {
    (Acceder a Crear Nota) --> (Rellenar Detalles)
    (Rellenar Detalles) --> (Guardar Cambios)
}

rectangle "Editar Nota" {

    (Seleccionar Nota a Editar) --> (Editar Detalles)
    (Editar Detalles) --> (Guardar Cambios) : <<include>>
}

rectangle "Eliminar Nota" {

    (Seleccionar Nota a Eliminar) --> (Confirmar Eliminación)
}

@enduml
