@startuml
actor Usuario

rectangle "Gestión de Lista de Tareas" {
    Usuario --> (Gestión de tarea en la lista de tareas)
    (Gestión de tarea en la lista de tareas) --> (Crear Tarea)
    (Gestión de tarea en la lista de tareas) --> (Editar Tarea)
    (Gestión de tarea en la lista de tareas) --> (Eliminar Tarea)
}

rectangle "Crear Tarea" {
    (Acceder a Crear Tarea) --> (Rellenar Detalles)
    (Rellenar Detalles) --> (Guardar Cambios)
}

rectangle "Editar Tarea" {
    (Seleccionar Tarea a Editar) --> (Editar Detalles)
    (Editar Detalles) --> (Guardar Cambios) : <<include>>
}

rectangle "Eliminar Tarea" {
    (Seleccionar Tarea a Eliminar) --> (Confirmar Eliminación)
}

@enduml
