@startuml
actor Usuario

rectangle "Gestionar cursos" {
  Usuario --> (Consultar todos los cursos)
  (Consultar todos los cursos) --> (Consultar curso)
  (Consultar todos los cursos) --> (Añadir curso): <<extend>>
  (Consultar curso) --> (Editar Curso): <<extend>>
  (Consultar curso) --> (Eliminar Curso): <<extend>>

}

@enduml
